id = "lume"
name = "Lume"
version = "0.1.1"
schema_version = 1
authors = ["Max T. Kristiansen <me@maxtrier.dk>"]
description = "Lume support."
repository = "https://github.com/lume-lang/extension-zed"

[grammars.lume]
repository = "https://github.com/lume-lang/tree-sitter-lume"
rev = "8e47087d09b498ae2120f272bc16f1ee2e5b5966"

[grammars.arc]
repository = "https://github.com/lume-lang/tree-sitter-arc"
rev = "6db039129a88734ce3366e0d62b8d5a593f931c2"
