name = "Arc"
grammar = "arc"
path_suffixes = ["Arcfile"]
line_comments = []
autoclose_before = "=]}"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "string_value",
    ] },
    { start = "'", end = "'", close = true, newline = false, not_in = [
        "string_value",
    ] },
]
